version: '3.7'
services:
  users:
    image: users
    ports:
      - 8080:8080
    depends_on:
      - user-db-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db-service:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
  user-db-service:
    image: mysql:latest
    ports: 
      - "8081:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=userdb
      - MYSQL_ONETIME_PASSWORD=true
    volumes:
      - ./data/:/var/lib/mysql