version: '2.0'

services:

  db-service:
    image: mysql:latest
    ports: 
      - "8080:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=eshop
      - MYSQL_ONETIME_PASSWORD=true
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      local_net:
        aliases:
          - db-service


  eureka:
    image: eureka
    build:
      context: ./eureka-server/eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      local_net:
        aliases:
          - eureka
    
  category-service:
    image: category-service
    ports:
      - "8088:8088"
    build:
      context: ./category-service/category-service
      dockerfile: ./Dockerfile
    depends_on:
      - db-service
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    networks:
      local_net:
        aliases:
          - category-service
    expose:
      - "8088"
    
  content-mgmt:
    image: content-mgmt
    ports:
      - "8089:8089"
    depends_on:
      - eureka
    build:
      context: ./content-management-service/content-management-service
      dockerfile: ./Dockerfile
    expose:
      - "8089"
    networks:
      local_net:
        aliases:
          - content-mgmt

    
    
  products:
    image: products
    ports:
      - "8084:8088"
    build:
      context: ./product-service/product-service
      dockerfile: ./Dockerfile
    depends_on:
      - db-service
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
    networks:
      local_net:
        aliases:
          - products
    

  users:
    image: users
    ports:
      - "8085:8088"
    build:
      context: ./user-service/user-service
      dockerfile: ./Dockerfile
    depends_on:
      - db-service
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
    networks:
      local_net:
        aliases:
          - users


  zuul:
    image: zuul
    build:
      context: ./zuul-server/zuul-server
      dockerfile: ./Dockerfile
    ports:
      - "8086:8062"
    depends_on:
      - eureka
    networks:
      local_net:
        aliases:
          - zuul

networks: 
  local_net:
    driver: bridge