version: '2.0'
services:
  
  db-service:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=eshop
      - MYSQL_ONETIME_PASSWORD=true
    volumes:
      - ./data/:/var/lib/mysql
    networks:
      local_net:
          aliases:
            - db-service
  
  eureka:
    build:
      context: ./eureka-server/eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      local_net:
        aliases:
          - eureka
  
  zuul:
    depends_on:
      - eureka
    build:
      context: ./zuul-server/zuul-server
      dockerfile: ./Dockerfile
    ports:
      - "8770:8770"
    networks:
      local_net:
        aliases:
          - zuul
  
  user-service:
    depends_on:
      - db-service
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
    build:
      context: ./user-service/user-service
      dockerfile: ./Dockerfile
    expose: 
      - "8762"
    networks:
      local_net:
        aliases:
          - user-service
  
  category-service:
    depends_on:
      - db-service
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
    build:
      context: ./category-service/category-service
      dockerfile: ./Dockerfile
    expose: 
      - "8766"
    networks:
      local_net:
        aliases:
          - category-service
  
  product-service:
    depends_on:
      - db-service
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
    build:
      context: ./product-service/product-service
      dockerfile: ./Dockerfile
    expose: 
      - "8764"
    networks:
      local_net:
        aliases:
          - product-service
  
  content-management-service:
    depends_on:
      - eureka
    build:
      context: ./content-management-service/content-management-service
      dockerfile: ./Dockerfile
    expose: 
      - "8768"
    networks:
      local_net:
        aliases:
          - content-management-service

  oauth-service:
    depends_on:
      - eureka
    build:
      context: ./oauth
      dockerfile: ./Dockerfile
    ports:
      - "8099:8099"
    networks:
      local_net:
        aliases:
          - oauth-service
          
  legacywebshop:
    build:
      context: ./eshop
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_net:
          aliases:
              - legacywebshop
  

networks: 
  local_net:
    driver: bridge