version: '3.7'

services:
  db-service:
    image: mysql:latest
    ports: 
      - "8080:3306"
    expose:
      - "8080"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=eshop
      - MYSQL_ONETIME_PASSWORD=true
    volumes:
      - ./data/:/var/lib/mysql

  eureka-srv:
    image: eureka
    build:
      context: ./eureka-server/eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    expose:
      - "8761"
    
  category-srv:
    image: categories
    ports:
      - "8088:8088"
    expose:
      - "8088"
    build:
      context: ./category-service/category-service
      dockerfile: ./Dockerfile
    depends_on:
      - db-service
      - eureka-srv
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://eureka:8761/eureka
    
  content-mgmt-srv:
    image: contents
    ports:
      - "8089:8089"
    expose:
      - "8089"
    depends_on:
      - eureka-srv
    build:
      context: ./content-management-service/content-management-service
      dockerfile: ./Dockerfile
    expose:
      - "8089"
 
  product-srv:
    image: products
    ports:
      - "8084:8084"
    expose: 
      - "8084"
    build:
      context: ./product-service/product-service
      dockerfile: ./Dockerfile
    depends_on:
      - db-service
      - eureka-srv
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
    
  user-srv:
    image: users
    ports:
      - "8085:8085"
    expose:
      - "8085"
    build:
      context: ./user-service/user-service
      dockerfile: ./Dockerfile
    depends_on:
      - db-service
      - eureka-srv
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3306/eshop?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
      
  zuul-srv:
    image: zuul
    build:
      context: ./zuul-server/zuul-server
      dockerfile: ./Dockerfile
    ports:
      - "8086:8086"
    expose:
      - "8086"
    depends_on:
      - eureka-srv