server:
	port: 8082
spring:
	application:
		name: user-service
	eureka:
		client:
			serverUrl:
				defaultZone: http://localhost:8761/eureka/
		instance:
			preferIpAddress: true
			leaseRenewalIntervalInSeconds: 5
			metadataMap:
				instanceId: "${spring.application.name}:${random.value}"