version: '3.7'
services:
  categories:
    image: categories
    ports:
      - 8084:8088
    depends_on:
      - category-db-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://category-db-service:3306/categorydb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
  category-db-service:
    image: mysql:latest
    ports: 
      - "8085:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=categorydb
      - MYSQL_ONETIME_PASSWORD=true
    volumes:
      - ./data/:/var/lib/mysql