server:
    port: 8768
spring:
    application:
        name: content-management
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 5
        metadataMap:
            instanceId: "${spring.application.name}:${random.value}"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    