server:
    port: 8089
spring:
    application:
        name: content-mgmt
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-srv:8761/eureka/
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 5
      metadataMap:
        instanceId: "${spring.application.name}:${random.value}"
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    