server:
  port: 8770
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  ignored-services: '*'
  routes:
    users:
      path: /users/**
      service-id: users
      strip-prefix: false
    content-management: /cms/**
    products: /auth/**
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 20000