server:
  port: 8770
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

zuul:
  sensitiveHeaders: 
  - Cookie,Set-Cookie
  ignoredHeaders:
  - authorization
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  ignored-services: '*'
  ribbon:
    eager-load:
      enabled: true
  routes:
    users:
      path: /users/**
      service-id: users
      strip-prefix: false
    content-management: /cms/**
    oauth:   
      path: /auth/**
      serviceId: oauth
      stripPrefix: false
      sensitiveHeaders: true
  