server:
  port: 8088

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

zuul:
  ignored-services:
  - '*'
  prefix: /webshop
  routes:
    user-service:
      path: /users/**
      service-id: user-service
      strip-prefix: false
    content-mgmt:
      path: /**
      service-id: content-mgmt
      strip-prefix: false

