server:
  port: 8770
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

zuul:
  ignored-services:
  - '*'
  prefix: /webshop
  routes:
    users:
      path: /users/**
      service-id: users
      strip-prefix: false
    content-management:
      path: /**
      service-id: content-management
      strip-prefix: true