version: '3.7'
services:
  products:
    image: products
    ports:
      - 8082:8088
    depends_on:
      - product-db-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://product-db-service:3306/productdb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=dbpass
  product-db-service:
    image: mysql:latest
    ports: 
      - "8083:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=productdb
      - MYSQL_ONETIME_PASSWORD=true
    volumes:
      - ./data/:/var/lib/mysql