server:
    port: 8088
spring:
    application:
        name: product-service
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://product-db-service:3306/productdb
        username: dbuser 
        password: dbpass
eureka:
    client:
        serverUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 5
        metadataMap:
            instanceId: "${spring.application.name}:${random.value}"